#!/bin/bash


for pid in $(ps -e -o pid);
do
	last_read_bytes=$(grep -s "read_bytes" "/proc/"$pid"/io" | grep -E -s -o "[0-9]+")
	if [[ -n $last_read_bytes ]];
	then
		echo "$pid:$last_read_bytes"
	fi
done > tmp

sleep 5s

for pid in $(ps -e -o pid);
do
	new_read_bytes=$(grep -s "read_bytes" "/proc/"$pid"/io" | grep -E -s -o "[0-9]+")
	if [[ -n $new_read_bytes ]];
	then
	last_read_bytes=$(cat tmp | grep "^$pid:"| cut -d ":" -f 2)
		if [[ -n $read_bytes ]];
		then
			read_bytes=$(echo  "scale=7; $new_read_bytes-$last_read_bytes" | bc -l)
			echo "$pid:$read_bytes"
		fi
	fi
done | sort -n -t ":" -k 2 -r |head -3
rm tmp

